### ISSUE TITLE
Invalid JSON response using create

### ISSUE THREAD

**Issue by mogenshoj** [noeticpenguin/ngForce#29]
Hi

I encountered a bug with the response from the create() method. I'm getting an error for invalid syntax:
Error: SyntaxError: JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data.

The console showed the response as:
```
{\"success\":true,\"errors\":[],\"id\":\"a0224000001COAKAA4\"}
```

Which should work.

But I put a console.log into the code before JSON.parse and saw this response:
```
{&quot;success&quot;:true,&quot;errors&quot;:[],&quot;id&quot;:&quot;a0224000001COAKAA4&quot;}
```

I'm not sure why it returns encoded characters for ". It works with every other call I've used so far (first create call I have used so far).

I solved the issue by putting a replace into the JSON.parse argument, like so:
```
a=JSON.parse(a.replace(/&quot;/ig,'"'))
```

I can't seem to find a non-minified version (is one publicly available?), so I had to do it in the minified version. I'm sure you can see where it belongs.

**Comment by mattwelch** [comment]
I think I might have figured out the problem here. On create (or update, or bulkUpdate).. pretty much anything except query or queryFromFieldset, the "this.standardOptions" passed in is undefined. For the aforementioned methods, the options are explicitly defined.

The end result of this is that the VF remoting default of escaping the result is in place. This is a "bad thing".

So we need to get those standardOptions defined at instantiation time.

**Comment by noeticpenguin** [comment]
I believe i've fixed this now.
