### ISSUE TITLE
Can't deploy test

### ISSUE THREAD

**Issue by westhechiang** [noeticpenguin/ngForce#36]
Hey there, for some odd reason I'm getting the following error when I try to deploy via Grunt: 
`System.QueryException: No such column 'billingaddress' on entity 'Account'. `

When I took a look at the deployment errors, here's what I saw:
```
System.QueryException: No such column 'billingaddress' on entity 'Account'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. 
Stack Trace: Class.ngForceController.sObjectKlone: line 237, column 1 Class.ngForceController_TEST.testSObjectKlone: line 304, column 1
```
I ended up commenting out the sObjectKlone method in the controller and the corresponding test in order to get ngForce deployed successfully. It's weird, my Googlefu isn't turning up any other users who experienced this...

Thanks for any ideas on what's going on here! Great job btw.

**Comment by noeticpenguin** [comment]
Wesley,

Good to hear from you. 

I just double checked in 3 orgs. the billingaddress field is a standard field on account. I know it wasn’t always that way, what API version is your org? If you’re using an older dev org, or if you’re using a pre-release org, that could be the issue?

Also, does your user have access to that field? I would normally suspect so, since you have deployment rights, but … better to be sure.

Regardless, we can change the tests for that to reflect a different set of fields.

-- 
Kevin Poorman
Sent with Airmail

On April 29, 2015 at 4:38:56 AM, Wesley Chiang (notifications@github.com) wrote:

Hey there, for some odd reason I'm getting the following error when I try to deploy via Grunt:
System.QueryException: No such column 'billingaddress' on entity 'Account'.

When I took a look at the deployment errors, here's what I saw:

System.QueryException: No such column 'billingaddress' on entity 'Account'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.  
Stack Trace: Class.ngForceController.sObjectKlone: line 237, column 1 Class.ngForceController_TEST.testSObjectKlone: line 304, column 1

I ended up commenting out the sObjectKlone method in the controller and the corresponding test in order to get ngForce deployed successfully. It's weird, my Googlefu isn't turning up any other users who experienced this...

Thanks for any ideas on what's going on here! Great job btw.

**Comment by noeticpenguin** [comment]
Wesley, 

I wanted to let you know I'm happy to help you get this working, but that I'm going to close this issue as the lack of a billingaddress field in your org is definitely not an issue with ngForce, but with your org. closing this issue won't stop commenting on it, so feel free to keep communication going here.
